### ISSUE TITLE
AtomicTech's To-do List

### ISSUE THREAD

**Issue by JamesErvin-5** [JamesErvin-5/AtomicTech-Inc.-Junkyards#9]
- [ ] Fix/Solve Nodes Issue.
- [ ] MoarKerbals Parts.
- [ ] MoarSolar Panels
- [ ] Big Science Bay.
- [ ] More EVA Suits.

**Comment by JamesErvin-5** [comment]
I also want to add this: https://spacedock.info/mod/2358/Mk2Y
